#!/usr/bin/env python3
"""
Plot the Robertson problem output generated by ./build/robertson_vode.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

import matplotlib.pyplot as plt


def parse_table(lines: List[str]) -> Dict[str, List[float]]:
    """
    Parse the text table produced by robertson_vode into column arrays.
    """
    columns = {"time": [], "y1": [], "y2": [], "y3": []}
    for raw in lines:
        line = raw.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 4:
            # Skip headers such as "time y1 y2 y3".
            continue
        try:
            values = list(map(float, parts))
        except ValueError:
            continue
        for key, value in zip(columns, values):
            columns[key].append(value)
    if not columns["time"]:
        raise ValueError("No numeric data found in input.")
    return columns


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot the Robertson problem abundances over time."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="robertson.log",
        help="Path to the tabulated output (default: robertson.log).",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Optional path to save the plot instead of showing it.",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.is_file():
        raise FileNotFoundError(
            f"Input file '{input_path}' does not exist. "
            "Generate it with './build/robertson_vode > robertson.log'."
        )

    lines = input_path.read_text().splitlines()
    data = parse_table(lines)

    plt.figure(figsize=(7, 4))
    for key, label in [("y1", "y1"), ("y2", "y2"), ("y3", "y3")]:
        plt.plot(data["time"], data[key], marker="o", label=label)
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel("time")
    plt.ylabel("abundance")
    plt.title("Robertson problem abundances")
    plt.legend()
    plt.tight_layout()

    if args.output:
        plt.savefig(args.output, bbox_inches="tight")
    else:
        plt.show()


if __name__ == "__main__":
    main()
